# Netlify Configuration for Static Next.js Export

[build]
  # Build command
  command = "npm run build"

  # Publish directory - Next.js static export output
  publish = "out"

  # Environment variables (if needed)
  # [build.environment]
  #   SITE_URL = "https://investment.advenoh.pe.kr"

# Redirect rules
[[redirects]]
  # Trailing slash normalization
  from = "/*"
  to = "/:splat/"
  status = 301
  force = false
  conditions = {path = ["!/*.html", "!/*.*"]}

[[redirects]]
  # 404 page
  from = "/*"
  to = "/404.html"
  status = 404

# Headers for caching and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://pagead2.googlesyndication.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://www.google-analytics.com; frame-src 'self' https://www.youtube.com;"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    # Long-term caching for Next.js static assets (1 year)
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/contents/*"
  [headers.values]
    # Long-term caching for blog content images (1 year)
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    # No caching for HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    # Sitemap caching (1 day)
    Cache-Control = "public, max-age=86400, s-maxage=86400"
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/rss.xml"
  [headers.values]
    # RSS feed caching (1 hour)
    Cache-Control = "public, max-age=3600, s-maxage=3600"
    Content-Type = "application/xml; charset=utf-8"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    # Robots.txt caching (1 day)
    Cache-Control = "public, max-age=86400, s-maxage=86400"
    Content-Type = "text/plain; charset=utf-8"

# Plugin configuration (optional)
# [[plugins]]
#   package = "@netlify/plugin-lighthouse"
